#Numpy basic



#Creating a numpy array and its attributes

In [ ]:
#importing numpy library
import numpy as np
#Creating a list named "my_list"
my_list = [1,2,3,4,5]
#creating a 1-D array from my_list
my_arr = np.array(my_list)
print(my_arr)


#creating a 0-D array
arr_0d = np.array(32)
print(arr_0d)

#Creating a 2D array
arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)

#Creating a 3D array
arr_3d = np.array([[1,2,3],[4,5,6],[7,8,9],[2,3,4]])
print(arr_3d)




[1 2 3 4 5]
32
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]
 [2 3 4]]


In [ ]:
#creating array and itd attributes
arr = np.array([[1,2,3,4],[6,7,8,9]])
print(arr)  #printing the array
print(arr.shape) #printing the shape of array
print(arr.ndim) #dimensions
print(arr.dtype) #datatype
print(arr.size) #size

[[1 2 3 4]
 [6 7 8 9]]
(2, 4)
2
int64
8


#Accessing and manipulating array elements

In [ ]:
#Accessing 1-D array elements
my_arr = np.array([2,4,5,6])
print(my_arr[2])

5


In [ ]:
#Accessing 2-D array elements
my_arr = np.array([[2,4,5,6],[11,3,4,5]])
print(my_arr[1,2])

4


In [ ]:
#Accessing 3-D array elements
my_arr = np.array([[[2,4,5,6],[1,3,4,5]],[[3,4,6,7],[2,3,4,4]]])
print(my_arr[0,1,2])

4


#Negative Indexing

In [ ]:
#Accessing 2-D array elements with negative indexing
my_arr = np.array([[2,4,5,6],[11,3,4,5]])
print(my_arr[1,-2])

4


#Slicing Arrays
####array[start:end]
####array[start:end:step]

In [ ]:
#Slicing 1-D numpy array
arr = np.array([1,2,3,6,5,7,8,4,3,20,33,22])
print(arr[1:5])  #Slicing
print(arr[1:5:2])  # slicing with step
print(arr[0:-1])   # Negative

[2 3 6 5]
[2 6]
[ 1  2  3  6  5  7  8  4  3 20 33]


In [ ]:
#slicing 2-D numpy array
arr = np.array([[1,3,5,7],[2,4,6,8]])
print(arr[1,1:-1])


#Homework: experiment with slicing on 3-D array


#Classwork

In [ ]:
#Creating a numpy array
arr = np.array([7,14,21,28])
print(arr)

[ 7 14 21 28]


In [ ]:
#Creating a 2-D numpy array
arr = np.array([[5,10,15],[20,25,30]])
print(arr.shape)
print(arr.ndim)

(2, 3)
2


In [ ]:
#
zeros_array = np.zeros((2,3))
arange_array = np.arange(0,13,3)
print(zeros_array)
print(arange_array)

[[0. 0. 0.]
 [0. 0. 0.]]
[ 0  3  6  9 12]


In [ ]:
#create a numpy array and multiply by 3
arr = np.array([2,4,6,8])
result = arr*3
print("result after multiplying by 3:", result)

result after multiplying by 3: [ 6 12 18 24]


In [ ]:
#create a numpy array and slice from index
arr = np.array([1,3,5,7,9,11])
print(arr[2])
print(arr[1:4])

5
[3 5 7]


#Classwork2

In [ ]:
#ques1
arr = np.random.randint(1,11, (3,3))
print(arr)
arr[arr > 5] = 0
print(arr)



[[ 1  7  6]
 [ 6 10  6]
 [ 6  4  9]]
[[1 0 0]
 [0 0 0]
 [0 4 0]]


In [ ]:
#ques2
a = np.array([2,4,6,8])
b = np.array([1,3,5,7])
print("element-wise sum:", a+b)
print("dot product:", np.dot(a,b))

element-wise sum: [ 3  7 11 15]
dot product: 100


In [ ]:
#ques3
arr = np.ones((4, 3))
addition = np.array([10, 20, 30])
result = arr + addition
print("Broadcasted addition result:\n", result)


Broadcasted addition result:
 [[11. 21. 31.]
 [11. 21. 31.]
 [11. 21. 31.]
 [11. 21. 31.]]


In [ ]:
#ques4
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
second_col = arr[:, 1]
mean_val = np.mean(second_col)
reshaped_arr = arr.reshape(-1)
print("Mean of second column:", mean_val)
print("Reshaped array:", reshaped_arr)

Mean of second column: 5.0
Reshaped array: [1 2 3 4 5 6 7 8 9]


In [ ]:
#ques5
arr = np.array([10, 20, 30, 40, 50, 60])
mask = arr > 30
squared = arr[mask] ** 2
print("Original array:", arr)
print("Squared elements > 30:", squared)

Original array: [10 20 30 40 50 60]
Squared elements > 30: [1600 2500 3600]
