#Linear algebra in AI

In [ ]:
import numpy as np
#creating a scaler
scaler = 9
print(scaler)

#creating a vetcors
vector = np.array([1,2,3])
print(vector)

#scaling a vector with a scaler aka. scaled vector
scaled_vector = scaler * vector
print(scaled_vector)

#creating a matrix
matrix = np.array([[1,2],[3,4]])
print(matrix)


9
[1 2 3]
[ 9 18 27]


#Vector addition and subtraction

In [ ]:
#vector addition
vector1 = np.array([1,2,3])
vector2 = np.array([4,5,6])
vector_sum = vector1 + vector2
print(vector_sum)

#vector subtraction
vector1 = np.array([1,2,3])
vector2 = np.array([4,5,6])
vector_sub = vector1 - vector2
print(vector_sub)


[5 7 9]
[-3 -3 -3]


#matrix creation and simple operation

In [ ]:
#matrix creation
matrix1 = np.array([[1,2],[3,4]])
matrix2 = np.array([[5,6],[7,8]])

print(matrix1)
print(matrix2)

#matrix addition
matrix_sum = matrix1 + matrix2
print(matrix_sum)

#matrix subtraction
matrix_sub = matrix1 - matrix2
print(matrix_sub)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]


#Matrix multiplication

In [ ]:
#Matrix multiplication
matrix1 = np.array([[2,4],[5,7]])
matrix2 = np.array([[6,8],[9,11]])
matrix_mul = np.dot(matrix1,matrix2)
print(matrix_mul)

[[ 48  60]
 [ 93 117]]


In [ ]:
#3*3 matrix multiplication
matrix1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
matrix2 = np.array([[2,4,6],[1,3,5],[2,7,8]])
matrix_mul = np.dot(matrix1,matrix2)
print(matrix_mul)

[[ 10  31  40]
 [ 25  73  97]
 [ 40 115 154]]


#matrix multiplication from scratch

In [ ]:
#matrix multiplication
matrix1 = np.array([[1,2],[3,4]])
matrix2 = np.array([[5,6],[7,8]])

matrix_mul[0][0] = matrix1[0,0] * matrix2[0,0] + matrix1[0,1] * matrix2[1,0]
matrix_mul[0][1] = matrix1[0,0] * matrix2[0,1] + matrix1[0,1] * matrix2[1,1]
matrix_mul[1][0] = matrix1[1,0] * matrix2[0,0] + matrix1[1,1] * matrix2[1,0]
matrix_mul[1][1] = matrix1[1,0] * matrix2[0,1] + matrix1[1,1] * matrix2[1,1]
print(matrix_mul)


# A more simplified approach!!!!!!!!!!!

a, b = matrix1[0]
c, d = matrix1[1]
e, f = matrix2[0]
g, h = matrix2[1]

mat_mul_index1 = a * e + b * g
mat_mul_index2 = a * f + b * h
mat_mul_index3 = c * e + d * g
mat_mul_index4 = c * f + d * h

print(mat_mul_index1, mat_mul_index2)
print(mat_mul_index3, mat_mul_index4)

[[19. 22.]
 [43. 50.]]


#identity matrix and transpose

In [ ]:
#identity matrix
identity = np.eye(2,dtype=int)
print(identity)

#transpose matrix
matrix1 = np.array([[2,4],[5,7]])
print(matrix1.T)

# matrix_transpose = np.transpose(matrix1)
# print(matrix_transpose)

[[1 0]
 [0 1]]
[[2 5]
 [4 7]]


#Matrix Inverse

In [ ]:
#matrix inverse
matrix1 = np.array([[2,4],[5,7]])
inverse = np.linalg.inv(matrix1)

identity = np.dot(matrix1, inverse)
print(identity)

[[1.0000000e+00 0.0000000e+00]
 [4.4408921e-16 1.0000000e+00]]


#Homework

In [ ]:
# Task 1: Create a vector [4, 5, 6] and multiply it by a scalar of 3. Print the result.
import numpy as np
vector = np.array([4,5,6])
scalar = 3
result = vector * scalar
print(result)

[12 15 18]


In [ ]:
# Task 2: Create two vectors [10, 20] and [5, 15]. Compute and print their sum
# and difference.
import numpy as np
vector1 = np.array([10,20])
vector2 = np.array([5,15])
vector_sum = vector1 + vector2
print(vector_sum)
vector_sub = vector1 - vector2
print(vector_sub)

[15 35]
[5 5]


In [ ]:
#Task 3: Create two 2x2 matrices [[2, 3], [4, 5]] and [[1, 1], [2, 2]]. Compute and
# print their sum.
import numpy as np
matrix1 = np.array([[2,3],[4,5]])
matrix2 = np.array([[1,1],[2,2]])
matrix_sum = matrix1 + matrix2
print(matrix_sum)


[[3 4]
 [6 7]]


In [ ]:
# Task 4: Create two 2x2 matrices [[1, 0], [0, 1]] and [[2, 3], [4, 5]]. Compute and
# print their product.
import numpy as np
matrix1 = np.array([[1,0],[0,1]])
matrix2 = np.array([[2,3],[4,5]])
matrix_mul = np.dot(matrix1,matrix2)
print(matrix_mul)

[[2 3]
 [4 5]]


In [ ]:
# Task 5: Create a 2x3 matrix [[10, 20, 30], [40, 50, 60]]. Compute and print its
# transpose. Also, create and print a 2x2 identity matrix.
import numpy as np
matrix1 = np.array([[10,20,30],[40,50,60]])
matrix_transpose = np.transpose(matrix1)
print(matrix_transpose)
identity = np.eye(2,dtype=int)
print(identity)

[[10 40]
 [20 50]
 [30 60]]
[[1 0]
 [0 1]]
